package pl.mobilization.speakermeter.dao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

	private final DaoConfig speakerDaoConfig;

	private final SpeakerDao speakerDao;

	public DaoSession(SQLiteDatabase db, IdentityScopeType type,
			Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
		super(db);

		speakerDaoConfig = daoConfigMap.get(SpeakerDao.class).clone();
		speakerDaoConfig.initIdentityScope(type);

		speakerDao = new SpeakerDao(speakerDaoConfig, this);

		registerDao(Speaker.class, speakerDao);
	}

	public void clear() {
		speakerDaoConfig.getIdentityScope().clear();
	}

	public SpeakerDao getSpeakerDao() {
		return speakerDao;
	}

}
